### ISSUE TITLE
When adding an offer, ensure that ethereum is also sent

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#19]
The amount of ethereum should match the amount in the offer.
Ex: Buy 1 Bitcoin with 10 ETH, should send 10 ETH to the contract.

**Comment by Glenapp** [comment]
I have added the validation for summiting the ETH when new offer is added  at UI and contract as well.
I have redeployed the smart contract on mumbai network. Since testnetwork is down.
Also updated test cases and contract in the second repo which is having the truffle contracts.

https://www.loom.com/share/4c9081087aa546eb9b99d3167ed75252

**Comment by svylabs** [comment]
<img width="1379" alt="Screenshot 2023-04-25 at 17 44 43" src="https://user-images.githubusercontent.com/64266123/234332232-604ab4b0-fec8-4279-8ad5-02777b0989df.png">

We need to look at this. It's not correct.

**Comment by Glenapp** [comment]
Resloved.https://www.loom.com/share/014d88628f684449864eb016f4ccbbc3
