### ISSUE TITLE
[Exchange page] Clicking on confirm should call the addOffer method in the contract

### ISSUE THREAD

**Issue by svylabs** [svylabs/trustlex-ui#8]
Clicking on "Confirm" in exchange page should add the offer to the contract.

1. After adding, and the transaction is successfully executed - the page should load the new offer and display to the user. We can use a similar design as below to display confirmation of the transaction.

<img width="1249" alt="Screenshot 2023-04-01 at 12 45 14" src="https://user-images.githubusercontent.com/64266123/229284342-fdd5c07d-c62a-4284-82d8-3abfbe9128d1.png">
 
<img width="1140" alt="Screenshot 2023-04-01 at 12 46 55" src="https://user-images.githubusercontent.com/64266123/229284349-64304955-9942-4071-93ea-7445e66d20b4.png">

3. It should also update the table with the new offer.
4. After 3 seconds, it should close the component, so that only offer table is shown.

**Comment by Glenapp** [comment]
Working on that

**Comment by Glenapp** [comment]
1-After adding, and the transaction is successfully executed - the page should load the new offer and display to the user. We can use a similar design as below to display confirmation of the transaction  -done.
2- It should also update the table with the new offer.   - Done
3-After 3 seconds, it should close the component, so that only offer table is shown. -done
